apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    ccss_score: "9.0"
    ccss_severity: Critical
    check_path: RoleBinding.roleRef.name|ClusterRoleBinding.roleRef.name|.roleRef.name
    description: The role cluster-admin provides wide-ranging powers over the environment and should be used only where and when needed
    expected: alert
    standards: "[{'standard': 'CIS Kubernetes Benchmark', 'version': '1.12', 'controls': ['5.1.1']}, {'standard': 'NSA-CISA Kubernetes Hardening Guide', 'controls': ['Role-Based Access Control']}, {'standard': 'BSI APP.4.4 Kubernetes', 'controls': ['APP.4.4.A9']}, {'standard': 'PCI Guidance for Containers and Container Orchestration Tools', 'controls': ['2.2.a']}, {'standard': 'Microsoft Threat Matrix for Kubernetes', 'controls': ['MS-M9003']}]"
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-001-2
  name: rbac-001-2-use-cluster-admin-role-cluster-wide-rb-cluster-admin
  namespace: kalm-benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: ""
    kind: Group
    name: rbac-001-2-use-cluster-admin-role-cluster-wide-sa
