apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    ccss_score: "4.0"
    ccss_severity: Medium
    check_path: RoleBinding.roleRef.name|ClusterRoleBinding.roleRef.name|.roleRef.name
    description: Bindings to system:anonymous or system:unauthenticated should be reviewed
    expected: alert
    standards: "[{'standard': 'Kubernetes Security Checklist', 'controls': ['Review bindings for the system:unauthenticated group and remove them where possible, as this gives access to anyone who can contact the API server at a network level.']}]"
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-027-3
  name: rbac-027-3-role-binds-to-anonymous-unauthenticated-rb-system:unauthenticated
  namespace: kalm-benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:unauthenticated
subjects:
  - apiGroup: ""
    kind: User
    name: rbac-027-3-role-binds-to-anonymous-unauthenticated-sa
