apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    check_path: ClusterRole.rules[].resources|Role.rules[].resources|.rules[].resources|ClusterRole.rules[].verbs|Role.rules[].verbs|.rules[].verbs
    description: Attackers who have permissions to retrieve the secrets can access sensitive information
    expected: alert
    standards: "[{'standard': 'CIS Kubernetes Benchmark', 'version': '1.12', 'controls': ['5.1.2']}, {'standard': 'NSA-CISA Kubernetes Hardening Guide', 'controls': ['Secrets']}, {'standard': 'BSI APP.4.4 Kubernetes', 'controls': ['APP.4.4.A9']}, {'standard': 'PCI Guidance for Containers and Container Orchestration Tools', 'controls': ['1.5.b']}, {'standard': 'Microsoft Threat Matrix for Kubernetes', 'controls': ['MS-M9003']}]"
  labels:
    app.kubernetes.io/part-of: kalm-benchmark
    check: RBAC-002-5
  name: rbac-002-5-secret-read-list
  namespace: kalm-benchmark
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
